--- #YAML:1.0
name:               Ogg-Theora-LibTheora
version:            0.02
abstract:           XS Interface for calling Theora Video Codec functions in Perl.
author:
    - Vigith Maurice <vigith@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Ogg::LibOgg:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
